// Copyright LBI-DHP and/or licensed to LBI-DHP under one or more
// contributor license agreements (LBI-DHP: Ludwig Boltzmann Institute
// for Digital Health and Prevention -- A research institute of the
// Ludwig Boltzmann Gesellschaft, Österreichische Vereinigung zur
// Förderung der wissenschaftlichen Forschung).
// Licensed under the Apache 2.0 license with Commons Clause
// (see https://www.apache.org/licenses/LICENSE-2.0 and
// https://commonsclause.com/).

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDBinNSCcWRcodBhf510j-KATwHTh6_HRc",
    authDomain: "aktivplanplus.firebaseapp.com",
    projectId: "aktivplanplus",
    storageBucket: "aktivplanplus.appspot.com",
    messagingSenderId: "717638915284",
    appId: "1:717638915284:web:9efc9e01dedf6457b41741",
    measurementId: "G-NJ3CHM0BG7",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcuG5UqWNte0sUlyuQwsMgmQw_IiysAWQ',
    appId: '1:717638915284:android:ba968065d132e9deb41741',
    messagingSenderId: '717638915284',
    projectId: 'aktivplanplus',
    storageBucket: 'aktivplanplus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABW0BlbZ2y0v7mhQJTL40lOBao4Lf9IIA',
    appId: '1:717638915284:ios:9c266bc5abcf7514b41741',
    messagingSenderId: '717638915284',
    projectId: 'aktivplanplus',
    storageBucket: 'aktivplanplus.appspot.com',
    iosClientId: '717638915284-n4t7nslr15ccv5pgrvd4erf61kih3ps7.apps.googleusercontent.com',
    iosBundleId: 'at.lbidhp.aktivplan',
  );
}
